### ISSUE TITLE
 The client noticed that the server is not a supported distribution of Elasticsearch

### ISSUE THREAD

**Issue by enimakherratia** [loopbackio/loopback-connector-elastic-search#140]
> Maintainers' Note: This question has been posted elsewhere:
> - https://stackoverflow.com/questions/69299381/the-client-noticed-that-the-server-is-not-a-supported-distribution-of-elasticsea

I'm using @elastic/elasticsearch version ^7.5.0 and Node 10.24.1. Everything worked fine, until  I redeploy my backend and since then I'm getting the following error:

The client noticed that the server is not a supported distribution of Elasticsearch

**Comment by achrinza** [comment]
See: https://github.com/elastic/elasticsearch-js/issues/1519

**Comment by enimakherratia** [comment]
any update?

**Comment by achrinza** [comment]
It's in my backlog, but no new updates to give. Will try to timebox by the end of the week if the CI migration goes smoothly. No promises at the moment though.

If its urgent, feel free to fork and pin the Elastic Search client v7 version  as per-https://github.com/loopbackio/loopback-connector-elastic-search/issues/140#issuecomment-925816337.

**Comment by achrinza** [comment]
Unfortunately I have not had the time to work on this repo.

For those looking for an immediate solution:

**NPM v8**

[NPM CLI v8.3.0](https://github.com/npm/cli/releases/tag/v8.3.0) onwards support [overrides](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides).

In `package.json`, add the following:

```json
"overrides": {
  "loopback-connector-elastic-search": {
    "es7": "@elastic/elasticsearch@7.13.0"
}
```

I've opened https://github.com/loopbackio/loopback-connector-elastic-search/issues/146 to track bringing this repo up to speed.
